#!/bin/bash
# ------------------------------------------------------------------
# [Author] Anton Horeis
#          This script starts the photogrammetry pipeline inside the meshroom docker container
# ------------------------------------------------------------------

VERSION=0.3
SUBJECT=some-unique-id
USAGE="Usage: photogrammetry [options] input_folder_name [meshroom_graph]"

# --- Options processing -------------------------------------------
if [ $# -le 1 ] ; then
    echo "$USAGE"
    exit 1;
fi

while getopts ":i:vhu:" optname
  do
    case "$optname" in
      "v")
        echo "Version $VERSION"
        exit 0;
        ;;
      "i")
        echo "-i argument: $OPTARG"
        ;;
      "h")
        echo $USAGE
        exit 0;
        ;;
      "u")
        u_id=$OPTARG
      ;;
      "?")
        echo "Unknown option $OPTARG"
        exit 0;
        ;;
      ":")
        echo "No argument value for option $OPTARG"
        exit 0;
        ;;
      *)
        echo "Unknown error while processing options"
        exit 0;
        ;;
    esac
  done

shift $(($OPTIND - 1))

input=$1
graph=${2:-"default_graph.mg"}
u_id=${u_id:-"default_user"}

# --- Locks -------------------------------------------------------
LOCK_FILE=/tmp/$SUBJECT.lock
if [ -f "$LOCK_FILE" ]; then
   echo "Script is already running"
   exit
fi

trap "rm -f $LOCK_FILE" EXIT
touch $LOCK_FILE

# --- Body --------------------------------------------------------
#  SCRIPT LOGIC GOES HERE
echo $input
echo $graph
#TODO add image compression

if [ ! -f /data/log/meshroom_output ]; then
    touch /data/log/meshroom_output
fi
if [ ! -d /data/model/"$input" ]; then
    mkdir -p /data/model/"$u_id"/"$input"
fi
if [ ! -f /data/log/obj2gltf_output ]; then
    touch /data/log/obj2gltf_output
fi

# Meshroom computation starts here
/opt/Meshroom/meshroom_batch --input /data/img_in/"$u_id"/"$input" --output /data/model/"$u_id"/"$input"/ -p photogrammetry >> /data/log/meshroom_output

#TODO copy logfiles to log volume

if [ -f /data/model/"$input"/texturedMesh.obj ] ; then
  obj2gltf -b -i /data/model/"$u_id"/"$input"/texturedMesh.obj -o /data/model/"$u_id"/"$input"/model.glb >> obj2gltf_output
else
  >&2 echo "Error: Couldn't find 3D Model. Probably, Meshroom failed while calculating the model. Check if enough ressources are available. Check Meshroom log."
fi


# -----------------------------------------------------------------
